Category.create!(name: 'fashion', priority: 1)
Category.create!(name: 'business', priority: 2)
Category.create!(name: 'sports', priority: 3)
Category.create!(name: 'entertainment', priority: 4)
Category.create!(name: 'magazine', priority: 5)
Category.create!(name: 'tv', priority: 6)