Category.create!(name: 'electric vehicles', priority: 1)
Category.create!(name: 'arduino', priority: 2)
Category.create!(name: 'machine learning', priority: 3)
Category.create!(name: 'embedded linux', priority: 4)
Category.create!(name: 'sensors', priority: 5)